version: "3"

services:
  webserver:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .htpasswd:/etc/nginx/.htpasswd
  app_note:
    build:
      context: .
      dockerfile: ./docker/php/php.dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db_mysql:/var/lib/mysql/
