version: "3"

services:
  webserver:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./docker/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - db

  app_note:
    build:
      context: .
      dockerfile: ./docker/php/php.dockerfile
    volumes:
      - ./:/var/www/html
  db:
    # platform: linux/x86_64 //For arm platform
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_mysql:/var/lib/mysql/
