<?php

namespace App\Providers;

// use Illuminate\Support\Facades\Gate;
use App\Contracts\Repositories\WordRepository;
use App\Contracts\Services\CategoryService;
use App\Contracts\Services\NoteService;
use App\Contracts\Services\WordService;
use App\Repositories\CategoryRepositoryImpl;
use App\Repositories\WordRepositoryImpl;
use App\Services\CategoryServiceImpl;
use App\Services\NoteServiceImpl;
use App\Services\WordServiceImpl;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class BootstrapServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    /**
     * @var array
     */
    public array $bindings = [
        WordService::class     => WordServiceImpl::class,
        CategoryService::class => CategoryServiceImpl::class,
        NoteService::class => NoteServiceImpl::class
    ];
}
