<?php

namespace App\Providers;

// use Illuminate\Support\Facades\Gate;
use App\Contracts\Repositories\CategoryRepository;
use App\Contracts\Repositories\NoteRepository;
use App\Contracts\Repositories\WordRepository;
use App\Repositories\CategoryRepositoryImpl;
use App\Repositories\NoteRepositoryImpl;
use App\Repositories\WordRepositoryImpl;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class RepositoryServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    /**
     * @var array
     */
    public array $bindings = [
        WordRepository::class     => WordRepositoryImpl::class,
        CategoryRepository::class => CategoryRepositoryImpl::class,
        NoteRepository::class => NoteRepositoryImpl::class
    ];
}
